name: Deployment
on: [push, pull_request]
jobs:
  build:
    name: "Build"
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          php_extensions: gd
  # test:
  #   ...
  deploy:
    name: "Deploy to DEV"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host dev
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}

      - name: Check out the source
        run: ssh dev 'cd /home4/kingpara/www/dev.drupal.am && git fetch && git reset --hard origin/master'
      
      - name: composer install
        run: ssh dev 'cd /home4/kingpara/www/dev.drupal.am && /opt/cpanel/composer/bin/composer install -n' 
      #- name: Start the server
      #  if: ${{ always() }}
      #  run: ssh staging 'sudo systemctl start my-application'

